# -*- coding: utf-8 -*-
"""modelagem_classificacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1801zYmRypW9WCyaQM0fbGzLS5JMoToft
"""

from google.colab import files
uploaded = files.upload()  # Clique no botão e selecione seu dataset_processado_atrasos.csv

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc, accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt
import seaborn as sns

# Carregando os dados
df = pd.read_csv('dataset_processado_atrasos.csv')

# Veja as primeiras linhas para conferir
df.head()

# Ajuste para as colunas do seu arquivo (exemplo abaixo)
X = df[['delay_days', 'delivery_time_days']]  # Adicione outras colunas se quiser
y = df['review_ruim']  # Alvo binário: 1 = review ruim, 0 = bom

X_train, X_test, y_train, y_test = train_test_split(
    X, y, stratify=y, test_size=0.3, random_state=42)

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
y_proba_rf = rf.predict_proba(X_test)[:, 1]

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)
y_proba_lr = lr.predict_proba(X_test)[:, 1]

# Random Forest
print("Random Forest")
print(classification_report(y_test, y_pred_rf))
# Logistic Regression
print("Logistic Regression")
print(classification_report(y_test, y_pred_lr))

plt.figure(figsize=(4,3))
sns.heatmap(confusion_matrix(y_test, y_pred_rf), annot=True, fmt='d', cmap='Blues')
plt.title('Matriz de Confusão - Random Forest')
plt.xlabel('Predito'); plt.ylabel('Real')
plt.savefig('matriz_confusao_rf.png')
plt.show()

fpr_rf, tpr_rf, _ = roc_curve(y_test, y_proba_rf)
roc_auc_rf = auc(fpr_rf, tpr_rf)
plt.figure()
plt.plot(fpr_rf, tpr_rf, label=f'Random Forest (AUC = {roc_auc_rf:.2f})')
plt.plot([0,1],[0,1],'k--')
plt.xlabel('FPR'); plt.ylabel('TPR'); plt.title('Curva ROC Random Forest')
plt.legend()
plt.savefig('roc_rf.png')
plt.show()

importances = pd.Series(rf.feature_importances_, index=X.columns)
importances.sort_values().plot(kind='barh')
plt.title('Importância das Features - Random Forest')
plt.savefig('feature_importance_rf.png')
plt.show()

resultados = pd.DataFrame({
    'Modelo': ['Random Forest', 'Logistic Regression'],
    'Acurácia': [accuracy_score(y_test, y_pred_rf), accuracy_score(y_test, y_pred_lr)],
    'Precisão': [precision_score(y_test, y_pred_rf), precision_score(y_test, y_pred_lr)],
    'Recall': [recall_score(y_test, y_pred_rf), recall_score(y_test, y_pred_lr)],
    'F1': [f1_score(y_test, y_pred_rf), f1_score(y_test, y_pred_lr)]
})
print(resultados)
resultados.to_csv('resultados_modelos.csv', index=False)

from google.colab import files
files.download('resultados_modelos.csv')
files.download('matriz_confusao_rf.png')
files.download('roc_rf.png')
files.download('feature_importance_rf.png')